"""Make calories column nullable

Revision ID: c46473592e6e
Revises: 231343d2887b
Create Date: 2024-05-17 22:22:45.742942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c46473592e6e'
down_revision: Union[str, None] = '231343d2887b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calorie_entries', 'calories',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calorie_entries', 'calories',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
